version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
    - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
    - 9092:9092
    depends_on:
    - zookeeper
    links:
    - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  cassandra:
    container_name: cassandra
    image: cassandra:3.11.1
    ports:
    - 7000:7000
    - 7001:7001
    - 9160:9160
    - 9042:9042
    - 7199:7199

  setup-cassandra:
    container_name: setup-cassandra
    build: ./setup-cassandra
    links:
    - cassandra
    command: bash -c "sleep 40 && echo Creating keyspace && cqlsh cassandra -f init.cql && sleep infinity"

  collector:
    build: ./collector
    container_name: collector
    image: tunahanpehlivan/collector
    restart: always
    ports:
    - 8080:8080
    depends_on:
    - kafka
    - cassandra
    links:
    - kafka:kafka
    - cassandra:cassandra

  recorder:
    build: ./recorder
    container_name: recorder
    image: tunahanpehlivan/recorder
    restart: always
    depends_on:
    - kafka
    - cassandra
    links:
    - kafka:kafka
    - cassandra:cassandra
